
#auth_service.py

import bcrypt
from services.user_factory import UserFactory
from database.user_queries import add_user, get_user_by_email, admin_exists


class AuthService:
    def __init__(self, db_manager):
        """Dependency injection of database manager."""
        self.db_manager = db_manager

    def hash_password(self, password):
                """Hash a plaintext password using bcrypt and return a UTF-8 string.

                Security notes:
                - Uses bcrypt with an autogenerated salt (`bcrypt.gensalt()`), producing
                    a salted hash appropriate for storage in `users.password_hash`.
                - Returns the hash as a UTF-8 decoded string so it can be stored in the DB.
                """
                raw_password = password.encode("utf-8")
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(raw_password, salt)
                return hashed_password.decode("utf-8")

    def verify_password(self, password, stored_hash):
                """Verify a plaintext password against the stored bcrypt hash.

                - Expects `stored_hash` as the UTF-8 string previously returned by
                    `hash_password()` and encodes it for `bcrypt.checkpw`.
                - Returns True only if the password matches; callers should avoid
                    leaking timing/boolean differences to callers beyond auth flow.
                """
                raw_password = password.encode("utf-8")
                stored_hash = stored_hash.encode("utf-8")
                return bcrypt.checkpw(raw_password, stored_hash)
    
    def admin_exists(self):
        return admin_exists(self.db_manager)
    
    def user_exists(self, email):
        user = get_user_by_email(self.db_manager, email)
        return user is not None
    
    def get_user_by_email(self, email):
        return get_user_by_email(self.db_manager, email)

    def register_user(self, full_name, email, password, phone=None, role="customer"):
        """Register a new user and return a domain `User` object.

        Business and DB rules:
        - Rejects duplicate emails by raising `ValueError`.
        - Normalizes `role` to lowercase and delegates user creation to `add_user`.
        - Passwords are stored as bcrypt hashes (see `hash_password`).
        - Returns a concrete `Customer` or `Admin` instance from `UserFactory`.
        """
        existing = get_user_by_email(self.db_manager, email)

        if existing:
            raise ValueError("Email already registered.")

        role_cleaned = role.strip().lower()
        password_hash = self.hash_password(password)

        user_id = add_user(
            self.db_manager,
            full_name,
            email,
            phone,
            password_hash,
            role_cleaned
        )

        new_user = UserFactory.create_user(
            role_cleaned,
            full_name,
            email,
            password_hash,
            phone,
            user_id
        )

        return new_user

    def login(self, email, password):
        """Authenticate a user and return a domain `User` on success, else None.

        - Fetches the user row by email; returns None if not found.
        - Verifies the password using bcrypt; on success constructs a `User`
          object via `UserFactory` preserving DB fields including `created_at`.
        - Does not raise on bad credentials (returns None) to keep the
          authentication flow simple for the CLI consumer.
        """
        user_row = get_user_by_email(self.db_manager, email)

        if not user_row:
            return None

        if self.verify_password(password, user_row["password_hash"]):
            return UserFactory.create_user(
                user_row["role"],
                user_row["full_name"],
                user_row["email"],
                user_row["password_hash"],
                user_row["phone"],
                user_row["user_id"],
                user_row["created_at"]
            )

        return None

   